### ISSUE TITLE
FromJSON deriver missing?

### ISSUE THREAD

**Issue by hughjfchen** [nikita-volkov/domain#3]
I can only see `toJsonDeriver` from the `domain-aeson` package but not `fromJsonDeriver`. Any plan to support this?

**Comment by nikita-volkov** [comment]
Yes. It's possible that it'll appear in the coming month, because I may get on the project that will require this. Otherwise PR will be much appreciated

**Comment by hughjfchen** [comment]
Well, I've tried but failed due to my limited experience of `template haskell`. But this feature is really really important for the `domain` library.

**Comment by nikita-volkov** [comment]
I have to agree. I'll give it higher priority. Can't promise to finish today, but I'm taking a look at it now.

**Comment by nikita-volkov** [comment]
Implemented in 0.1.1

**Comment by hughjfchen** [comment]
Wow, that's impressive. Thanks for your prompt response on this. I'm really appreciated.
